/*
 * This source file was generated by the Gradle 'init' task
 */
package minggu2;

abstract class hewan {
    private String name;
    private int age;
    private String food;

    public hewan(String name, int age, String food) {
        this.name = name;
        this.age = age;
        this.food = food;

    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getFood() {
        return food;
    }

    public void setFood(String food) {
        this.food = food;
    }

    public abstract String printSound();

    public String printData() {
        return "Nama : " + name + " ;Age : " + age + "tahun ;Food: " + food;
    }
}

abstract class hewandarat extends hewan {
    private int numberOflegs;

    public hewandarat(String name, int age, String food, int numberOflegs) {
        super(name, age, food);
        this.numberOflegs = numberOflegs;
    }

    public int getNumberOflegs() {
        return numberOflegs;
    }

    public void setNumberOflegs(int numberOflegs) {
        this.numberOflegs = numberOflegs;
    }

    public void move() {
        System.out.println(getName() + "Berjalan Atau Berlari Menggunakan " + numberOflegs+ " Kaki");
    }

    @Override
    public String printData() {
        return super.printData() + ", Jumlah Kaki : " + numberOflegs;
    }

}

class anjing extends hewandarat {
    public anjing(String name, int age, String food, int numberOflegs) {
        super(name, age, food, numberOflegs);
    }

    public String printSound() {
        return "GUK GUK";
    }
}

class kucing extends hewandarat {
    public kucing(String name, int age, String food, int numberOflegs) {
        super(name, age, food, numberOflegs);
    }

    public String printSound() {
        return "MEOW MEOW";
    }
}

class tikus extends hewandarat {
    public tikus(String name, int age, String food, int numberOflegs) {
        super(name, age, food, numberOflegs);
    }

    public String printSound() {
        return "CIT CIT";
    }
}

abstract class hewanlaut extends hewan{
    private double depth;

    public hewanlaut(String name, int age, String food, double depth) {
        super(name, age, food);
        this.depth = depth;
    }

    public double getdepth() {
        return depth;
    }

    public void setdepth(double depth) {
        this.depth = depth;
    }

    @Override
    public String printData() {
        return super.printData() + ", Tinggal di kedalaman " + depth +"m";
    }

}

class ikan extends hewanlaut  {
    public ikan(String name, int age, String food, double depth) {
        super(name, age, food, depth);
    }

    public String printSound() {
        return "Blub Blub";
    }
}

class hiu extends hewanlaut {
    public hiu(String name, int age, String food, double depth) {
        super(name, age, food, depth);
    }

    public String printSound() {
        return "Splash";
    }
}

class paus extends hewanlaut {
    public paus(String name, int age, String food, double depth) {
        super(name, age, food, depth);
    }

    public String printSound() {
        return "Whistle";
    }
}

abstract class hewanudara extends hewan{
    private double wingSpan;

    public hewanudara(String name, int age, String food, double wingSpan) {
        super(name, age, food);
        this.wingSpan = wingSpan;
    }

    public double getwingSpan() {
        return wingSpan;
    }

    public void setwingSpan(int wingSpan) {
        this.wingSpan = wingSpan;
    }

    @Override
    public String printData() {
        return super.printData() + ", Memiliki Sayap Selebar : " + wingSpan + " Cm";
    }

}

class burung extends hewanudara {
    public burung(String name, int age, String food, double wingSpan) {
        super(name, age, food, wingSpan);
    }

    public String printSound() {
        return "CUIT CUIT";
    }
}

class elang extends hewanudara {
    public elang(String name, int age, String food, double wingSpan) {
        super(name, age, food, wingSpan);
    }

    public String printSound() {
        return "Kreeee";
    }
}

class bebek extends hewanudara {
    public bebek(String name, int age, String food, double wingSpan) {
        super(name, age, food, wingSpan);
    }

    public String printSound() {
        return "Kwek Kwek";
    }
}

public class Main {
    public static void main(String[] args) {
        hewan[] daftarHewan = new hewan[] {
                new anjing("Doggy", 3, "Tulang", 4),
                new kucing("Milo", 2, "Ikan", 4),
                new tikus("Jerry", 1, "Keju", 4),
                new ikan("Nemo", 1, "Plankton", 15.0),
                new hiu("Megalo", 10, "Daging", 500.0),
                new paus("Bluey", 20, "Krill", 1000.0),
                new burung("Pipit", 1, "Biji-bijian", 0.2),
                new elang("Garuda", 5, "Daging", 2.1),
                new bebek("Donald", 2, "Dedak", 0.8)
        };
        for (hewan h : daftarHewan) {
            System.out.println(h.printData());
            System.out.println("Suara : " + h.printSound());
            System.out.println("----------------------------------------");
        }
    }
}